---
title: "Exploring data"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(modelr)
library(dplyr)
library(ggplot2)
library(countrycode)
library(readxl)
library(xlsx)
```

________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


Cross country government expenditure CSV



```{r}
cross_country_gov_spend_mental_health <- read_csv("data/Cross country Government expenditure on mental health.csv") %>% 
  clean_names() %>% 
  filter(x1 != "Country") %>% 
  mutate(country = x1) %>% 
  select(-x1) %>% 
  select(country, government_expenditures_on_mental_health_as_a_percentage_of_total_government_expenditures_on_health_percent, government_expenditures_on_mental_hospitals_as_a_percentage_of_total_government_expenditures_on_mental_health_percent, stand_alone_mental_health_legislation, mental_health_plan, mental_health_policy
) %>% 
  mutate(gov_spend_mental_health_percent = government_expenditures_on_mental_health_as_a_percentage_of_total_government_expenditures_on_health_percent,
         gov_spend_mental_hospitals_of_mh_spend_percent =  government_expenditures_on_mental_hospitals_as_a_percentage_of_total_government_expenditures_on_mental_health_percent, 
         number = 1:182) %>% 
  select(-government_expenditures_on_mental_health_as_a_percentage_of_total_government_expenditures_on_health_percent, -government_expenditures_on_mental_hospitals_as_a_percentage_of_total_government_expenditures_on_mental_health_percent)


cross_country_gov_spend_mental_health %>% 
  filter(stand_alone_mental_health_legislation == "Yes",
         mental_health_plan == "Yes",
         mental_health_policy == "Yes")


continents <- as.tibble(countrycode(sourcevar = cross_country_gov_spend_mental_health$country,
                            origin = "country.name",
                            destination = "continent")) %>% 
  mutate(number = 1:182)

cross_country_gov_spend_mental_health_w_continents <-
left_join(continents, cross_country_gov_spend_mental_health, by = "number") %>% 
  mutate(continent = value) %>% 
  select(-value, -number)


cross_country_gov_spend_mental_health_w_continents

```

________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


Commuing Data XLSX


```{r}
commuting_data_usual_method_of_travel <-
read.xlsx2("data/Commuting Data UK.xlsx", 2) %>% 
  tail(-4) %>%   
  mutate(gender = as.character(X..1),
         work_region = as.character(X..3),
         no_answer = as.character(X..4),
         car_van_minibus_works_van	 = as.character(X..5),
         motorbike_moped_scooter	= as.character(X..6),
         bicycle = as.character(X..7),
         bus_coach_private_bus = as.character(X..8),
         taxi = as.character(X..9),
         railway_train = as.character(X..10),
         underground_train_light_railway_tram = as.character(X..11),
         walk = as.character(X..12),
         other_method = as.character(X..13)
         ) %>%
  select(-c(X..1:X..17), 
         -X.) %>% 
  mutate(no_answer = as.numeric(no_answer),
         car_van_minibus_works_van	 = as.numeric(car_van_minibus_works_van),
         motorbike_moped_scooter	= as.numeric(motorbike_moped_scooter),
         bicycle = as.numeric(bicycle),
         bus_coach_private_bus = as.numeric(bus_coach_private_bus),
         taxi = as.numeric(taxi),
         railway_train = as.numeric(railway_train),
         underground_train_light_railway_tram = as.numeric(underground_train_light_railway_tram),
         walk = as.numeric(walk),
         other_method = as.numeric(other_method)
         )
 

# commuting_data_usual_method_of_travel %>% 
#  fill(gender, .direction = "up")

  
commuting_data_usual_method_of_travel
  
#WHY IS FILL NOT WORKING?

```


```{r}
commuting_data_time_taken <-
read.xlsx2("data/Commuting Data UK.xlsx", 4)  %>% 
  tail(-4) %>% 
  mutate(gender = as.character(X..1),
         work_region = as.character(X..3),
         x1_to_15 = as.character(X..4),
         x16_to_30	 = as.character(X..5),
         x31_to_45	= as.character(X..6),
         x46_to_60 = as.character(X..7),
         over_60 = as.character(X..8)
         ) %>% 
  select(-c(X..1:X..16), 
         -X.) %>% 
  mutate(x1_to_15 = as.numeric(x1_to_15),
         x16_to_30	 = as.numeric(x16_to_30),
         x31_to_45	= as.numeric(x31_to_45),
         x46_to_60 = as.numeric(x46_to_60),
         over_60 = as.numeric(over_60)

         
         ) %>% 
  head(-3)


commuting_data_time_taken 

#FILL ALSO NOT WORKING HERE



```


```{r}
commuting_data_car_travel_status_male_female_proportion <-
read.xlsx2("data/Commuting Data UK.xlsx", 6) %>% 
    tail(-4) %>% 
  mutate(gender = as.character(X..1),
         work_region = as.character(X..3),
         no_answer = as.character(X..4),
         driver	 = as.character(X..5),
         passenger	= as.character(X..6),
         both = as.character(X..7)
         ) %>% 
  select(-c(X..1:X..17), 
         -X.) %>% 
  mutate(no_answer = as.numeric(no_answer),
         driver	 = as.numeric(driver),
         passenger	= as.numeric(passenger),
         both = as.numeric(both)
         )

commuting_data_car_travel_status_male_female_proportion

```


```{r}
commuting_data_travel_time_male_female_proportion <-
read.xlsx2("data/Commuting Data UK.xlsx", 7) %>% 
   tail(-4) %>% 
  mutate(gender = as.character(X..1),
         work_region = as.character(X..3),
         x1_to_15 = as.character(X..4),
         x16_to_30	 = as.character(X..5),
         x31_to_45	= as.character(X..6),
         x46_to_60 = as.character(X..7),
         over_60 = as.character(X..8)
         ) %>% 
  select(-c(X..1:X..16), 
         -X.) %>% 
  mutate(x1_to_15 = as.numeric(x1_to_15),
         x16_to_30	 = as.numeric(x16_to_30),
         x31_to_45	= as.numeric(x31_to_45),
         x46_to_60 = as.numeric(x46_to_60),
         over_60 = as.numeric(over_60)

         
         ) %>% 
  head(-3)

commuting_data_travel_time_male_female_proportion 
```


```{r}
read.xlsx2("data/Commuting Data UK.xlsx", 8)
```

some dataframes missing from xlsx


________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



```{r}
read_xls("data/Cross country Gross Domestic Spending on R&D.xls")
```









________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________

```{r}
cross_country_infrastructure_investment <-
read_xls("data/Cross country infrastructure investment.xls") %>% 
  clean_names() %>% 
  select(-indicator) %>% 
  mutate(alpha_3_code = location,
         subject = str_to_lower(subject))

unique(cross_country_infrastructure_investment$subject)

country_codes <-
read_csv("own_data/countries_codes_and_coordinates.csv") %>% 
  clean_names() %>% 
  select(country, alpha_3_code)

country_codes

cross_country_infrastructure_investment <-
inner_join(country_codes, cross_country_infrastructure_investment, by = "alpha_3_code") %>% 
  select(-c(alpha_3_code, location, frequency, flag_codes))

cross_country_infrastructure_investment_eur <-
  cross_country_infrastructure_investment %>% 
  filter(measure == "EUR")

cross_country_infrastructure_investment_eur

cross_country_infrastructure_investment_gdp <-
  cross_country_infrastructure_investment %>% 
  filter(measure != "EUR")

cross_country_infrastructure_investment_gdp

write_csv("clean_data/cross_country_infrastructure_investment_gdp.csv")

```





________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




```{r}
cross_country_mental_health_infrastructure <-
read_csv("data/Cross Country Mental Health.csv") %>% 
  clean_names() %>% 
  rename(country = x1,
         x2011_mental_hospitals_per_100k = mental_hospitals_per_100_000,
         x2010_mental_health_units_per_gen_hospital_per_100k = mental_health_units_in_general_hospitals_per_100_000,
         x2009_mental_health_units_per_gen_hospital_per_100k = mental_health_units_in_general_hospitals_per_100_000_1,
         x2008_mental_health_units_per_gen_hospital_per_100k = mental_health_units_in_general_hospitals_per_100_000_2,
         x2007_mental_health_units_per_gen_hospital_per_100k = mental_health_units_in_general_hospitals_per_100_000_3,
         x2006_mental_health_units_per_gen_hospital_per_100k = mental_health_units_in_general_hospitals_per_100_000_4,
         x2005_mental_health_units_per_gen_hospital_per_100k = mental_health_units_in_general_hospitals_per_100_000_5,
         x2004_mental_health_units_per_gen_hospital_per_100k = mental_health_units_in_general_hospitals_per_100_000_6,
         x2011_mental_health_outpatient_facilities_per_100k = mental_health_outpatient_facilities_per_100_000,
         x2011_mental_health_day_treatment_facilities_per_100k = mental_health_day_treatment_facilities_per_100_000,
         x2011_community_residential_facilities_per_100k = community_residential_facilities_per_100_000
         
         ) %>% 
  tail(-1)

cross_country_mental_health_infrastructure %>% 
  

```
























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________



























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________




























________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________


















________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________